package id.go.lan.ikk.seeder;

import id.go.lan.ikk.entity.AgencyCategoryEnum;
import id.go.lan.ikk.module.user.entity.AgencyEntity;
import id.go.lan.ikk.module.user.repository.AgencyRepository;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

@Component
@Order(value = 3)
@Slf4j
public class AgencySeeder implements CommandLineRunner {

    @Autowired
    private AgencyRepository agencyRepository;

    @Override
    public void run(String... args) {
        try {
            seed();
        } catch (Exception e) {
            log.error(e.getMessage());
        }
    }

    private void seed() {
        if (agencyRepository.count() == 0) {
            agencyRepository.save(new AgencyEntity("Kementerian Koordinator Bidang Politik, Hukum dan Keamanan", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Koordinator Bidang Perekonomian", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Koordinator Bidang Kemaritiman dan Investasi", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Sekretariat Negara", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Dalam Negeri", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Luar Negeri", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Pertahanan", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Agama", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Hukum dan Hak Asasi Manusia", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Keuangan", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Pendidikan dan Kebudayaan", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Kesehatan", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Sosial", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Ketenagakerjaan", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Perindustrian", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Perdagangan", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Energi dan Sumber Daya Mineral", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Pekerjaan Umum dan Perumahan Rakyat", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Perhubungan", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Komunikasi dan Informatika", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Pertanian", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Lingkungan Hidup dan Kehutanan", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Kelautan dan Perikanan", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Desa, Pembangunan Daerah Tertinggal, dan Transmigrasi", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Agraria dan Tata Ruang (Badan Pertanahan Nasional)", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Perencanaan Pembangunan Nasional (Bappenas)", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Badan Usaha Milik Negara", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Koperasi dan Usaha Kecil dan Menengah", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Pariwisata dan Ekonomi Kreatif", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Pemberdayaan Perempuan dan Perlindungan Anak", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Kementerian Pemuda dan Olahraga", AgencyCategoryEnum.valueOf("KEMENTERIAN")));
            agencyRepository.save(new AgencyEntity("Dewan Perwakilan Rakyat", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Dewan Perwakilan Daerah", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Pemeriksa Keuangan", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Mahkamah Agung", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Mahkamah Konstitusi", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Komisi Yudisial", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Tentara Nasional Indonesia", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Kepolisian Negara Republik Indonesia", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Kejaksaan Agung", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Bank Indonesia", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Komisi Pemilihan Umum", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Komisi Pemberantasan Korupsi", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Komisi Penyiaran Indonesia", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Pusat Pelaporan dan Analisis Traksaksi Keuangan", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Ombudsman Republik Indonesia", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Otoritas Jasa Keuangan", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Lembaga Penjamin Simpanan", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Komisi Nasional Hak Asasi Manusia", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Komisi Pengawas Persaingan Usaha", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Komisi Perlindungan Anak Indonesia", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Pengawas Pemilihan Umum", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("BPJS Kesehatan", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("BPJS Ketenagakerjaan", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Informasi Geospasial", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Intelijen Negara", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Keamanan Laut Republik Indonesia", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Kepegawaian Negara", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Kependudukan dan Keluarga Berencana Nasional", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Koordinasi Penanaman Modal", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Meteorologi, Klimatologi, dan Geofisika", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Narkotika Nasional", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Nasional Penanggulangan Bencana", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Nasional Penanggulangan Terorisme", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Nasional Pencarian dan Pertolongan", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Perlindungan Pekerja Migran Indonesia", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Pengawas Keuangan dan Pembangunan", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Pengawas Tenaga Nuklir", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Pengawas Obat dan Makanan", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Pengkajian dan Penerapan Teknologi", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Pusat Statistik", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Siber dan Sandi Negara", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Standardisasi Nasional", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Tenaga Nuklir Nasional", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Lembaga Administrasi Negara", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Lembaga llmu Pengetahuan Indonesia / Badan Riset dan Inovasi Nasional (BRIN)", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Lembaga Kebijakan Pengadaan Barang/Jasa Pemerintah", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Lembaga Penerbangan dan Antariksa Nasional", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Perpustakaan Nasional Republik Indonesia", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Arsip Nasional Republik Indonesia", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Amil Zakat Nasional", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Nasional Sertifikasi Profesi", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Nasional Pengelola Perbatasan", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Pengelola Keuangan Haji", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Dewan Jaminan Sosial Nasional", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Komisi Aparatur Sipil Negara", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Komisi Kejaksaan", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Komisi Kepolisian Nasional", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Lembaga Perlindungan Saksi dan Korban", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Badan Pembinaan Ideologi Pancasila", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Televisi Republik Indonesia", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Radio Republik Indonesia", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Majelis Permusyawaratan Rakyat", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Sekretariat Kabinet", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Aceh Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Aceh Barat Daya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Aceh Besar", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Aceh Jaya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Aceh Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Aceh Singkil", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Aceh Tamiang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Aceh Tengah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Aceh Tenggara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Aceh Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Aceh Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bener Meriah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bireuen", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Gayo Lues", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Nagan Raya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pidie", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pidie Jaya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Simeulue", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Banda Aceh", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Langsa", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Lhokseumawe", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Sabang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Subulussalam", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Asahan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Batu Bara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Dairi", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Deli Serdang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Humbang Hasundutan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Karo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Labuhanbatu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Labuhanbatu Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Labuhanbatu Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Langkat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Mandailing Natal", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Nias", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Nias Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Nias Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Nias Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Padang Lawas", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Padang Lawas Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pakpak Bharat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Samosir", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Serdang Bedagai", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Simalungun", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tapanuli Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tapanuli Tengah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tapanuli Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Toba Samosir", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Binjai", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Gunungsitoli", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Medan", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Padangsidempuan", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Pematangsiantar", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Sibolga", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Tanjungbalai", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Tebing Tinggi", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Agam", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Dharmasraya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kepulauan Mentawai", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lima Puluh Kota", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Padang Pariaman", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pasaman", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pasaman Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pesisir Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sijunjung", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Solok", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Solok Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tanah Datar", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Bukittinggi", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Padang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Padangpanjang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Pariaman", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Payakumbuh", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Sawahlunto", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Solok", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bengkalis", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Indragiri Hilir", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Indragiri Hulu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kampar", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kepulauan Meranti", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kuantan Singingi", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pelalawan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Rokan Hilir", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Rokan Hulu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Siak", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Dumai", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Pekanbaru", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bintan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Karimun", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kepulauan Anambas", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lingga", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Natuna", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Batam", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Tanjung Pinang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Batanghari", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bungo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kerinci", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Merangin", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Muaro Jambi", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sarolangun", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tanjung Jabung Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tanjung Jabung Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tebo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Jambi", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Sungaipenuh", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bengkulu Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bengkulu Tengah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bengkulu Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kaur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kepahiang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lebong", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Mukomuko", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Rejang Lebong", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Seluma", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Bengkulu", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Banyuasin", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Empat Lawang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lahat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Muara Enim", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Musi Banyuasin", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Musi Rawas", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Musi Rawas Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Ogan Ilir", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Ogan Komering Ilir", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Ogan Komering Ulu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Ogan Komering Ulu Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Ogan Komering Ulu Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Penukal Abab Lematang Ilir", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Lubuklinggau", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Pagar Alam", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Palembang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Prabumulih", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bangka", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bangka Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bangka Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bangka Tengah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Belitung", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Belitung Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Pangkal Pinang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lampung Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lampung Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lampung Tengah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lampung Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lampung Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Mesuji", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pesawaran", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pesisir Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pringsewu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tanggamus", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tulang Bawang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tulang Bawang Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Way Kanan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Bandar Lampung", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Metro", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lebak", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pandeglang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Serang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tangerang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Cilegon", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Serang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Tangerang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Tangerang Selatan", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bandung", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bandung Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bekasi", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bogor", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Ciamis", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Cianjur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Cirebon", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Garut", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Indramayu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Karawang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kuningan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Majalengka", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pangandaran", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Purwakarta", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Subang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sukabumi", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sumedang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tasikmalaya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Bandung", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Banjar", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Bekasi", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Bogor", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Cimahi", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Cirebon", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Depok", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Sukabumi", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Tasikmalaya", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Administrasi Kepulauan Seribu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Administrasi Jakarta Barat", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Administrasi Jakarta Pusat", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Administrasi Jakarta Selatan", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Administrasi Jakarta Timur", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Administrasi Jakarta Utara", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Banjarnegara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Banyumas", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Batang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Blora", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Boyolali", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Brebes", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Cilacap", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Demak", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Grobogan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Jepara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Karanganyar", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kebumen", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kendal", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Klaten", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kudus", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Magelang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pati", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pekalongan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pemalang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Purbalingga", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Purworejo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Rembang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Semarang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sragen", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sukoharjo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tegal", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Temanggung", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Wonogiri", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Wonosobo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Magelang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Pekalongan", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Salatiga", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Semarang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Surakarta", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Tegal", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bantul", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Gunungkidul", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kulon Progo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sleman", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Yogyakarta", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bangkalan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Banyuwangi", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Blitar", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bojonegoro", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bondowoso", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Gresik", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Jember", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Jombang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kediri", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lamongan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lumajang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Madiun", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Magetan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Malang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Mojokerto", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Nganjuk", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Ngawi", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pacitan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pamekasan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pasuruan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Ponorogo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Probolinggo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sampang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sidoarjo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Situbondo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sumenep", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Trenggalek", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tuban", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tulungagung", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Batu", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Blitar", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Kediri", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Madiun", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Malang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Mojokerto", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Pasuruan", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Probolinggo", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Surabaya", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Badung", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bangli", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Buleleng", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Gianyar", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Jembrana", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Karangasem", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Klungkung", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tabanan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Denpasar", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bima", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Dompu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lombok Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lombok Tengah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lombok Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lombok Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sumbawa", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sumbawa Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Bima", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Mataram", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Alor", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Belu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Ende", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Flores Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kupang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lembata", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Malaka", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Manggarai", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Manggarai Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Manggarai Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Nagekeo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Ngada", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Rote Ndao", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sabu Raijua", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sikka", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sumba Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sumba Barat Daya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sumba Tengah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sumba Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Timor Tengah Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Timor Tengah Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Kupang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bengkayang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kapuas Hulu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kayong Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Ketapang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kubu Raya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Landak", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Melawi", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Mempawah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sambas", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sanggau", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sekadau", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sintang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Pontianak", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Singkawang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Balangan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Banjar", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Barito Kuala", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Hulu Sungai Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Hulu Sungai Tengah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Hulu Sungai Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kotabaru", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tabalong", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tanah Bumbu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tanah Laut", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tapin", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Banjarbaru", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Banjarmasin", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Barito Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Barito Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Barito Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Gunung Mas", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kapuas", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Katingan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kotawaringin Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kotawaringin Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lamandau", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Murung Raya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pulang Pisau", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sukamara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Seruyan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Palangka Raya", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Berau", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kutai Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kutai Kartanegara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kutai Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Mahakam Ulu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Paser", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Penajam Paser Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Balikpapan", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Bontang", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Samarinda", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bulungan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Malinau", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Nunukan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tana Tidung", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Tarakan", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Boalemo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bone Bolango", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Gorontalo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Gorontalo Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pohuwato", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Gorontalo", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Majene", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Mamasa", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Mamuju", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Mamuju Tengah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pasangkayu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Polewali Mandar", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bantaeng", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Barru", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bone", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bulukumba", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Enrekang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Gowa", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Jeneponto", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kepulauan Selayar", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Luwu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Luwu Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Luwu Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Maros", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pangkajene dan Kepulauan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pinrang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sidenreng Rappang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sinjai", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Soppeng", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Takalar", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tana Toraja", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Toraja Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Wajo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Makassar", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Palopo", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Parepare", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bombana", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Buton", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Buton Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Buton Tengah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Buton Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kolaka", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kolaka Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kolaka Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Konawe", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Konawe Kepulauan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Konawe Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Konawe Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Muna", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Muna Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Wakatobi", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Bau-Bau", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Kendari", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Banggai", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Banggai Kepulauan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Banggai Laut", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Buol", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Donggala", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Morowali", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Morowali Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Parigi Moutong", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Poso", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sigi", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tojo Una-Una", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tolitoli", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Palu", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bolaang Mongondow", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bolaang Mongondow Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bolaang Mongondow Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Bolaang Mongondow Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kepulauan Sangihe", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kepulauan Siau Tagulandang Biaro", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kepulauan Talaud", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Minahasa", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Minahasa Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Minahasa Tenggara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Minahasa Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Bitung", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Kotamobagu", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Manado", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Tomohon", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Buru", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Buru Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kepulauan Aru", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Maluku Barat Daya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Maluku Tengah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Maluku Tenggara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kepulauan Tanimbar", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Seram Bagian Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Seram Bagian Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Ambon", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Tual", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Halmahera Barat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Halmahera Tengah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Halmahera Timur", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Halmahera Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Halmahera Utara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kepulauan Sula", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pulau Morotai", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pulau Taliabu", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Ternate", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kota Tidore Kepulauan", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Asmat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Biak Numfor", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Boven Digoel", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Deiyai", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Dogiyai", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Intan Jaya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Jayapura", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Jayawijaya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Keerom", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kepulauan Yapen", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Lanny Jaya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Mamberamo Raya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Mamberamo Tengah", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Mappi", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Merauke", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Mimika", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Nabire", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Nduga", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Paniai", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pegunungan Bintang", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Puncak", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Puncak Jaya", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sarmi", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Supiori", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tolikara", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Waropen", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Yahukimo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Yalimo", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Jayapura", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Kabupaten Fakfak", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Kaimana", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Manokwari", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Manokwari Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Maybrat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Pegunungan Arfak", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Raja Ampat", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sorong", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Sorong Selatan", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Tambrauw", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Teluk Bintuni", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kabupaten Teluk Wondama", AgencyCategoryEnum.valueOf("KABUPATEN")));
            agencyRepository.save(new AgencyEntity("Kota Sorong", AgencyCategoryEnum.valueOf("KOTA")));
            agencyRepository.save(new AgencyEntity("Lembaga Ketahanan Nasional", AgencyCategoryEnum.valueOf("LEMBAGA")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Banten", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Jawa Barat", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah DKI Jakarta", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Jawa Tengah", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah DI Yogyakarta", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Jawa Timur", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Bali", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Nusa Tenggara Barat", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Nusa Tenggara Timur", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Kalimantan Barat", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Kalimantan Selatan", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Kalimantan Tengah", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Kalimantan Timur", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Kalimantan Utara", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Gorontalo", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Sulawesi Barat", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Sulawesi Selatan", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Sulawesi Tenggara", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Sulawesi Tengah", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Sulawesi Utara", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Maluku", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Maluku Utara", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Papua", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Papua Barat", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah DI Aceh", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Sumatera Utara", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Sumatera Barat", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Riau", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Kepulauan Riau", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Jambi", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Bengkulu", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Sumatera Selatan", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Kepulauan Bangka Belitung", AgencyCategoryEnum.valueOf("PROVINSI")));
            agencyRepository.save(new AgencyEntity("Pemerintah Daerah Provinsi Lampung", AgencyCategoryEnum.valueOf("PROVINSI")));
        }
    }
}
