package id.go.lan.ikk.entity;

public enum PolicyStatusEnum {
    BELUM_TERVERIFIKASI,
    MENUNGGU_VERIFIKASI,
    SEDANG_VERIFIKASI,
    SELESAI_VERIFIKASI,
    MENUNGGU_VALIDASI_AI,
    MENUNGGU_VALIDASI_KI,
    SEDANG_VALIDASI_KI,
    SELESAI_VALIDASI_KI,
    MENUNGGU_VALIDASI_KU,
    SEDANG_VALIDASI_KU,
    SELESAI_VALIDASI_KU,
    TELAH_DITERBITKAN,
}
